Module Sequence:
Case step of 
Initialization:
Hmi.Sequence.MainSeqSubState :="Test";
(*Transition*)
Stopped:
Hmi.Sequence.MainSeqSubState :="Test";
(*Transition*)
 Starting: 
Hmi.Sequence.MainSeqSubState :="Test";
(*Transition*)
Running:
Hmi.Sequence.MainSeqSubState :="Test";
(*Transition*)
Stopping:
Hmi.Sequence.MainSeqSubState :="Test";
(*Transition*)
Emergency_Shutodown:
Hmi.Sequence.MainSeqSubState :="Test";
(*Transition*)